#!/bin/bash
#今天这个视频我来教给大家如何编译Firefly RK3399的安卓系统（Android7.1）
#首先我们从官网下载源代码https://pan.baidu.com/s/1nwqaptR?_at_=1684040991356#list/path=%2F
#编译环境我们使用Ubuntu16.04 64bit
#设置虚拟内存
sudo dd if=/dev/zero of=/swapfile bs=1M count=18432
sudo mkswap /swapfile
sudo swapon /swapfile
#在 /etc/fstab 文件中加入一行代码：
/var/swapfile swap swap defaults 0 0
#安装依赖
sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt-get install openjdk-8-jdk htop vim git gnupg flex bison gperf libsdl1.2-dev libesd-java libwxgtk3.0-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev schedtool g++-multilib lib32z1-dev lib32ncurses5-dev lib32readline-dev gcc-multilib libswitch-perl libssl-dev unzip zlib1g-dev libbz2-dev libssl-dev libncurses5-dev libsqlite3-dev libreadline-dev tk-dev libgdbm-dev libdb-dev libpcap-dev xz-utils libexpat1-dev liblzma-dev libffi-dev libc6-dev p7zip-rar -y
sudo apt-get clean
#验证md5值（可忽略）
md5sum ~/firefly_rk3399_industry7.1_git_20211216.7z.00*
#解压源码
7z x ~/firefly_rk3399_industry7.1_git_20211216.7z.001 -r -o.
#指定版本
git reset --hard
#更新仓库
7z x rk3399-industry-nougat-bundle.7z  -r -o. && mv rk3399-industry-nougat-bundle/ .bundle/
#更新SDK
.bundle/update
#同步Firefly分支
git rebase FETCH_HEAD
#设置配置文件
#修改prebuilts/sdk/tools/jack-admin，找到以下内容：
JACK_SERVER_COMMAND="java -XX:MaxJavaStackTraceDepth=-1 -Djava.io.tmpdir=$TMPDIR $JACK_SERVER_VM_ARGUMENTS -cp $LAUNCHER_JAR $LAUNCHER_NAME"
改为：
JACK_SERVER_COMMAND="java -XX:MaxJavaStackTraceDepth=-1 -Djava.io.tmpdir=$TMPDIR $JACK_SERVER_VM_ARGUMENTS -Xmx4096M -cp $LAUNCHER_JAR $LAUNCHER_NAME"
#安装Jack
cd prebuilts/sdk/tools/
./jack-admin install-server jack-launcher.jar jack-server-4.8.ALPHA.jar
#删除/etc/java-8-openjdk/security/java.security 文件里jdk.tls.disabledAlgorithms 的 TLSv1, TLSv1.1
#重新启动Jack-server
./prebuilts/sdk/tools/jack-admin kill-server 
./prebuilts/sdk/tools/jack-admin start-server
#使用官方脚本编译
./FFTools/make.sh  -d rk3399-firefly-aio -j"n" -l rk3399_firefly_aio-userdebug
#打包镜像
./FFTools/mkupdate/mkupdate.sh -l rk3399_firefly_aio-userdebug
#使用AOSP编译模式
#初始化环境
source build/envsetup.sh
#选择设备
lunch
#编译
make -j"n"
#最后我们将out目录的文件打包或直接刷
#烧写到设备（省略）
#擦除Flash
sudo upgrade_tool ef update.img
#烧写
sudo upgrade_tool uf update.img
#编译成功后，执行下面的命令，就可以打开Android模拟器，开始使用自己编译的系统了。
emulator
#好，那么今天的视频就到这里了，感谢观看
